version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - /root/data/mongod:/root/data
      - /root/logs/mongod:/root/logs
    networks:
      - propel-backend-network
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    container_name: redis
    volumes:
      - /root/data/redis:/data
      - /root/logs/redis:/logs
    networks:
      - propel-backend-network
    ports:
      - "6379:6379"

  propel-backend:
    image: evia-propel-backend:latest
    restart: always
    container_name: propel-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/propel
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    ports: 
      - "3000:3000"
    networks:
      - propel-backend-network

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./certbot-conf/nginx:/etc/nginx/conf.d
      - ./certbot-conf/certbot/conf:/etc/letsencrypt
      - ./certbot-conf/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - propel-backend
    networks:
      - propel-backend-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:arm64v8-latest
    container_name: certbot
    volumes:
      - ./certbot-conf/certbot/conf:/etc/letsencrypt
      - ./certbot-conf/certbot/www:/var/www/certbot
    depends_on:
      - propel-backend
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  propel-backend-network:
    driver: bridge  